### ISSUE TITLE
Responsive issues in mobile view

### ISSUE THREAD

**Issue by Ambiplatforms-TORQUE** [TORQUE-AMBIPLATFORMS/Torquehq-website#3]
## Summary of Bug

The website is showing issues with responsiveness in the mobile view when opening the about us section.

## Version

Issue persistent till commit [2594038](https://github.com/TORQUE-AMBIPLATFORMS/Torquehq-website/commit/259403832e86f934293a422e4faf0b1d4c972bbc)

## Steps to Reproduce

Switch to mobile view in the browser via inspect section.

## Additional context

The issue seems to originate from a minor bug in the [index.ejs](https://github.com/TORQUE-AMBIPLATFORMS/Torquehq-website/blob/main/views/pages/index.ejs) file.
____

## For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by Purvesh-ambiplatforms** [comment]
Can I work on the issue?

**Comment by Ambiplatforms-TORQUE** [comment]
Issue is still visible even after the new updates.
